kyua: import kyua-0.15.0-beta1
This change adds kyua kyua-0.15.0-beta1 from [upstream][1].

The kyua-0.15.0-beta1 artifact was been verified by [SHA256 checksum][3].

This change contains a number of new features and bugfixes, as well as
the official upstreaming of several features previously committed to the
FreeBSD src tree.

More information about the release (from a high level) can be found in
the [release notes][4].

Updated via [`update_kyua.sh`][4] `update_kyua.sh 0.15.0-beta1 kyua-0.15.0`.

1: https://github.com/freebsd/kyua/releases/download/kyua-0.15.0-beta1/kyua-0.15.0-beta1.tar.gz
2: https://github.com/freebsd/kyua/releases/download/kyua-0.15.0-beta1/kyua-0.15.0-beta1.tar.gz.sha256
3: https://github.com/freebsd/kyua/blob/kyua-0.15.0-beta1/NEWS.md
4: https://codeberg.org/ngie/freebsd-powertools:shell/update_kyua.sh@10a04edb

diff --git a/Makefile.am b/Makefile.am
--- a/Makefile.am
+++ b/Makefile.am
@@ -26,6 +26,30 @@
 # (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 # OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
+CODE_COVERAGE_DIRS =
+
+#
+# Supporting logic to run our custom testsuite.
+#
+
+TESTS_ENVIRONMENT = PKG_CONFIG_PATH=$(prefix)/lib/pkgconfig
+
+if HAVE_ASAN
+# NB: the trailing comma is intentional. I hate automake not allowing `:=` use on subsequent lines.
+if HAVE_LSAN
+LSAN_OPTIONS = detect_leaks=1,
+else
+LSAN_OPTIONS =
+endif
+# Some of the testcases trigger false positives as they pass
+# `SIZE_MAX - 1`, etc, to malloc(3).
+ASAN_OPTIONS = ${LSAN_OPTIONS}allocator_may_return_null=1
+TESTS_ENVIRONMENT+= ASAN_OPTIONS=${ASAN_OPTIONS}
+endif
+if HAVE_UBSAN
+TESTS_ENVIRONMENT+= UBSAN_OPTIONS=print_stacktrace=1:halt_on_error=1:report_error_type=1
+endif
+
 ACLOCAL_AMFLAGS = -I m4
 
 CHECK_BOOTSTRAP_DEPS =
@@ -38,10 +62,10 @@ CLEANFILES =
 
 EXTRA_DIST =
 noinst_DATA =
-noinst_LIBRARIES =
+noinst_LTLIBRARIES =
 noinst_SCRIPTS =
 
-doc_DATA = AUTHORS CONTRIBUTING.md CONTRIBUTORS LICENSE NEWS.md
+doc_DATA = AUTHORS CONTRIBUTING.md CONTRIBUTORS LICENSE NEWS
 noinst_DATA += INSTALL.md README.md
 EXTRA_DIST += $(doc_DATA) INSTALL.md README.md
 
@@ -62,13 +86,14 @@ include examples/Makefile.am.inc
 include integration/Makefile.am.inc
 include misc/Makefile.am.inc
 include model/Makefile.am.inc
+include os/freebsd/Makefile.am.inc
 include store/Makefile.am.inc
 include utils/Makefile.am.inc
 
 bin_PROGRAMS = kyua
 kyua_SOURCES = main.cpp
 kyua_CXXFLAGS = $(CLI_CFLAGS) $(ENGINE_CFLAGS) $(UTILS_CFLAGS)
-kyua_LDADD = $(CLI_LIBS) $(ENGINE_LIBS) $(UTILS_LIBS)
+kyua_LDADD = $(CLI_LIBS) $(ENGINE_LIBS) $(FREEBSD_LIBS) $(UTILS_LIBS)
 
 CHECK_ENVIRONMENT = KYUA_CONFDIR="/non-existent" \
                     KYUA_DOCDIR="$(abs_top_srcdir)" \
@@ -108,20 +133,42 @@ check-kyua: $(CHECK_KYUA_DEPS)
 	    exit 1; \
 	fi
 
-installcheck-local: dump-ulimits installcheck-kyua
+INSTALLCHECK_TARGETS =
 PHONY_TARGETS += installcheck-kyua
+INSTALLCHECK_TARGETS += dump-ulimits installcheck-kyua
 installcheck-kyua:
-	@failed=no; \
 	cd $(pkgtestsdir) && $(INSTALLCHECK_ENVIRONMENT) $(TESTS_ENVIRONMENT) \
-	    kyua --config='$(KYUA_CONFIG_FILE_FOR_CHECK)' test \
-	    || failed=yes; \
-	if [ "$${failed}" = yes ]; then \
-	    cd $(pkgtestsdir) && $(INSTALLCHECK_ENVIRONMENT) \
-	        $(TESTS_ENVIRONMENT) \
-	        kyua --config='$(KYUA_CONFIG_FILE_FOR_CHECK)' report \
-	        --verbose --results-filter=broken,failed; \
-	    exit 1; \
-	fi
+	    kyua --config='$(KYUA_CONFIG_FILE_FOR_CHECK)' test; \
+	ret=$$?; \
+	echo $${ret}; \
+	if [ -n "$$JUNIT_OUTPUT" ]; then \
+	    cd $(pkgtestsdir) && $(TESTS_ENVIRONMENT) \
+		    $(KYUA) --config='$(KYUA_CONFIG_FILE_FOR_CHECK)' \
+		    report-junit --output="$$JUNIT_OUTPUT"; \
+	    sed -i '.orig' 's/encoding="iso-8859-1"/encoding="utf-8"/' "$$JUNIT_OUTPUT"; \
+	    rm -f "$$JUNIT_OUTPUT.orig"; \
+	fi; \
+	cd $(pkgtestsdir) && $(INSTALLCHECK_ENVIRONMENT) $(TESTS_ENVIRONMENT) \
+	    kyua --config='$(KYUA_CONFIG_FILE_FOR_CHECK)' report \
+	    --verbose --results-filter=broken,failed; \
+	exit $${ret}
+
+if CODE_COVERAGE
+CODE_COVERAGE_EXCLUDES = '/usr/include/*' '/usr/local/include/*'
+CODE_COVERAGE_OUTPUT_DIR ?= code_coverage
+EXTRA_GENHTML_ARGS ?=
+INSTALLCHECK_TARGETS+=	installcheck-kyua-lcov
+
+installcheck-kyua-lcov: installcheck-kyua
+	mkdir -p $(CODE_COVERAGE_OUTPUT_DIR)/html
+	$(LCOV) --capture --directory $(srcdir) \
+	    --output-file $(CODE_COVERAGE_OUTPUT_DIR)/lcov.info
+	$(LCOV) --remove $(CODE_COVERAGE_OUTPUT_DIR)/lcov.info \
+	    $(CODE_COVERAGE_EXCLUDES) \
+	    --output-file $(CODE_COVERAGE_OUTPUT_DIR)/lcov-filtered.info
+	$(GENHTML) -o $(CODE_COVERAGE_OUTPUT_DIR)/html $(EXTRA_GENHTML_ARGS) \
+	    $(CODE_COVERAGE_OUTPUT_DIR)/lcov-filtered.info
+endif
 
 # TODO(jmmv): kyua should probably be recording this information itself as part
 # of the execution context, just as we record environment variables.
@@ -134,14 +181,24 @@ dump-ulimits:
 	} | sort | sed -e 's,^,    ,'
 	@echo
 else
-DIST_HOOKS += forbid-dist
-PHONY_TARGETS += forbid-dist
-forbid-dist:
-	@echo "Sorry; cannot make dist without atf."
+DIST_HOOKS += dist-no-atf
+PHONY_TARGETS += dist-no-atf
+dist-no-atf:
+	@echo "Sorry; cannot build a distfile without atf"
 	@false
 endif
 check-local: $(CHECK_LOCAL)
 
+if CODE_COVERAGE
+PHONY_TARGETS += mostlyclean-code-coverage
+mostlyclean-local: mostlyclean-code-coverage
+mostlyclean-code-coverage:
+	-for dir in $(CODE_COVERAGE_DIRS); do \
+	    find $$dir \( -name \*.gcda -or -name \*.gcno \) -delete -print; \
+	done
+endif
+
+installcheck-local: $(INSTALLCHECK_TARGETS)
 if WITH_DOXYGEN
 # Runs doxygen on the source tree and validates the contents of the docstrings.
 # We do not do this by default, even if doxygen has been enabled, because this
@@ -164,23 +221,26 @@ clean-api-docs:
 endif
 
 # Replace Automake's builtin check-news functionality so that we can validate
-# the NEWS.md file instead of NEWS.
+# the NEWS file instead of NEWS.
 DIST_HOOKS += check-news
 PHONY_TARGETS += check-news
 check-news:
-	@case "$$(sed 15q "$(srcdir)/NEWS.md")" in \
+	@case "$$(sed 15q "$(srcdir)/NEWS")" in \
 	*"$(VERSION)"*) : ;; \
 	*) \
-	    echo "NEWS.md not updated; not releasing" 1>&2; \
+	    echo "NEWS not updated; not releasing" 1>&2; \
 	    exit 1 \
 	    ;; \
 	esac
 
 clean-local: $(CLEAN_TARGETS)
-dist-hook: $(DIST_HOOKS)
 
 PHONY_TARGETS += clean-all
 clean-all:
 	GIT="$(GIT)" $(SH) $(srcdir)/admin/clean-all.sh
 
+dist-hook: $(DIST_HOOKS)
+
 .PHONY: $(PHONY_TARGETS)
+
+# vim: syntax=make:noexpandtab:shiftwidth=8:softtabstop=8
